"""Change phone number field type from int to varchar

Revision ID: 177cbbd7238c
Revises: 3ef310cd9649
Create Date: 2024-06-07 17:53:32.767342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '177cbbd7238c'
down_revision = '3ef310cd9649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'telefono',
                    existing_type=sa.Integer(),
                    type_=sa.String(length=35),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'telefono',
                    existing_type=sa.String(length=35),
                    type_=sa.Integer(),
                    existing_nullable=False)
    # ### end Alembic commands ###
